### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by Haley-Wami** [foerstner-lab/READemption#24]
Hello,

I am trying to install (via pip) READemption and run into an error. 
I have all the requirements (Ubuntu packages, segemehl v0.2.0, DESeq2) installed and functional. However, running bin/reademption -h gives the following error. 

Traceback (most recent call last):
  File "bin/reademption", line 6, in <module>
    from reademptionlib.controller import Controller
  File "/home/haley/.local/lib/python3.5/site-packages/reademptionlib/controller.py", line 15, in <module>
    from reademptionlib.readaligner import ReadAligner
  File "/home/haley/.local/lib/python3.5/site-packages/reademptionlib/readaligner.py", line 1, in <module>
    from reademptionlib.segemehl import Segemehl
  File "/home/haley/.local/lib/python3.5/site-packages/reademptionlib/segemehl.py", line 68
    tmp_sorted_outfile = f"{output_file}_sorted"
                                               ^
SyntaxError: invalid syntax
 
I downloaded the .tar.gz and run make also gives me the following issue.
ERROR tests/test_controller.py
ERROR tests/test_segemehl.py

I appreciate any help in advance!

**Comment by Tillsa** [comment]
Hello!
Thank you for reporting the error. I assume the error occurs because you are using python version 3.5 which does NOT support f-strings. Line 68 is using an f-string. Could you please install a newer version that is at least 3.6, where f-strings have been introduced and then try again. And please let me know if it worked.

Best regards,
Till

**Comment by Haley-Wami** [comment]
Hello Till,

That fixed the issue thanks a lot for your help!

Kind regards,
Haley

**Comment by Tillsa** [comment]
You're welcome!
